name: CI

on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install system dependencies
              run: sudo apt update && sudo apt-get -y install libusb-1.0-0-dev libasound2-dev libudev-dev

            - name: Install nodejs dependencies
              run: npm ci

            - name: Build TS
              run: npm run build

    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install system dependencies
              run: sudo apt update && sudo apt-get -y install libusb-1.0-0-dev libasound2-dev libudev-dev

            - name: Install nodejs dependencies
              run: npm ci

            - name: Run tests
              run: npm run coverage -- --verbose
      nodecg:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install nodecg-cli
              run: npm install --global nodecg-cli
            - name: Setup NodeCG
              run: nodecg setup
            - name: Setup NodeCG config
              run: |
                  mkdir cfg
                  echo '{"bundles": {"paths": ["'${GITHUB_WORKSPACE}'/nodecg-io","'${GITHUB_WORKSPACE}'/nodecg-io/services","'${GITHUB_WORKSPACE}'/nodecg-io/samples"]}}' > ./cfg/nodecg.json
            - uses: actions/checkout@v2
              with:
                  path: "nodecg-io"
            - name: Install system dependencies
              run: sudo apt update && sudo apt-get -y install libusb-1.0-0-dev libasound2-dev libudev-dev
            - name: Install nodejs dependencies
              run: cd nodecg-io && npm ci
            - name: Build Typescript
              run: cd nodecg-io && npm run build
            - name: Run test
              run: cd nodecg-io && node .scripts/ci-nodecg-integration.mjs

