name: test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18"

      - name: Install system dependencies
        run: sudo apt update && sudo apt-get -y install libusb-1.0-0-dev libasound2-dev libudev-dev

      - name: Possible Fix
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/alsa-lib/ /usr/lib64/alsa-lib

      - name: Install nodejs dependencies
        run: npm ci

      - name: Run easymidi
        run: npm run test
