name: test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18"

      - name: Install system dependencies
        run: sudo apt update && sudo apt-get -y install libusb-1.0-0-dev libasound2-dev libudev-dev

      - name: Link stuff (1/3)
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0 /usr/lib64/libasound.so.2.0.0

      - name: Link stuff (2/3)
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0 /usr/lib64/libasound.so.2

      - name: Link stuff (3/3)
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0 /usr/lib64/libasound.so

      - name: Some tests
        run: ls -la /usr/lib/x86_64-linux-gnu && ls -la /usr/lib64

      - name: Install nodejs dependencies
        run: npm ci

      - name: Run easymidi
        run: npm run test
