name: test

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "18"

      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libusb-1.0-0-dev libasound2-dev libudev-dev

      - name: Patch \#1030 (ubuntu 20.04)
        if: matrix.os == 'ubuntu-latest'
        continue-on-error: true
        run: |
           sudo chown -R $USER:audio /dev/snd/

      - name: Debug
        continue-on-error: true
        run: |
          groups
          ls -lah /dev/snd/

      - name: Install nodejs dependencies
        run: npm ci

      - name: Run easymidi
        run: npm run test
